SearchBayesianSkopt: Config 0 Exception. Config: {'topK': 382, 'shrink': 498, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.1717859936517083, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 1 Exception. Config: {'topK': 875, 'shrink': 305, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.9821626864255777, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 2 Exception. Config: {'topK': 924, 'shrink': 732, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.884913633190692, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 3 Exception. Config: {'topK': 118, 'shrink': 149, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.0172341399243443, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 4 Exception. Config: {'topK': 503, 'shrink': 734, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.749460924423174, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 5 Exception. Config: {'topK': 12, 'shrink': 980, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.0743973912367927, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 6 Exception. Config: {'topK': 1000, 'shrink': 18, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.9788809036537023, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 7 Exception. Config: {'topK': 1000, 'shrink': 928, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.0005557629775269253, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 8 Exception. Config: {'topK': 93, 'shrink': 16, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.15314498408775667, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 9 Exception. Config: {'topK': 6, 'shrink': 912, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.9472538846043659, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 10 Exception. Config: {'topK': 974, 'shrink': 31, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.00980562891599446, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 11 Exception. Config: {'topK': 7, 'shrink': 70, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.9326669371100196, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 12 Exception. Config: {'topK': 955, 'shrink': 987, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.0, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 13 Exception. Config: {'topK': 25, 'shrink': 923, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.9764431612630762, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 14 Exception. Config: {'topK': 24, 'shrink': 2, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.02760126777657535, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 15 Exception. Config: {'topK': 989, 'shrink': 987, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.1934692286398741, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 16 Exception. Config: {'topK': 20, 'shrink': 5, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.09533301566109567, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 17 Exception. Config: {'topK': 991, 'shrink': 33, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.9930196083940226, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 18 Exception. Config: {'topK': 83, 'shrink': 990, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.01827668103360934, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 19 Exception. Config: {'topK': 970, 'shrink': 932, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.993385204823336, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 20 Exception. Config: {'topK': 1000, 'shrink': 993, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.9799136306742524, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 21 Exception. Config: {'topK': 972, 'shrink': 7, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.028558475541640378, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 22 Exception. Config: {'topK': 20, 'shrink': 992, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.9771790620670793, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 23 Exception. Config: {'topK': 986, 'shrink': 29, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.9236390185288565, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 24 Exception. Config: {'topK': 19, 'shrink': 64, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.9635583161613206, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 25 Exception. Config: {'topK': 63, 'shrink': 991, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.012590565094494726, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 26 Exception. Config: {'topK': 26, 'shrink': 988, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.11776821457320141, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 27 Exception. Config: {'topK': 963, 'shrink': 70, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.008770777912574525, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 28 Exception. Config: {'topK': 23, 'shrink': 75, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.9641196378510644, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 29 Exception. Config: {'topK': 53, 'shrink': 12, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.0, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 30 Exception. Config: {'topK': 978, 'shrink': 996, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.870916166556325, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 31 Exception. Config: {'topK': 979, 'shrink': 977, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.13436961745232082, 'feature_weighting': 'none'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 32 Exception. Config: {'topK': 20, 'shrink': 993, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.023793625019483462, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 33 Exception. Config: {'topK': 999, 'shrink': 36, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 0.05995780040919875, 'feature_weighting': 'BM25'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Config 34 Exception. Config: {'topK': 30, 'shrink': 986, 'similarity': 'asymmetric', 'normalize': True, 'asymmetric_alpha': 1.9990970175117682, 'feature_weighting': 'TF-IDF'} - Exception: Traceback (most recent call last):
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 335, in _objective_function
    current_fit_parameters_dict)
  File "C:\Users\ALEXDRUSO\Desktop\RecSysChallenge2020\src\ParameterTuning\SearchAbstractClass.py", line 242, in _evaluate_on_validation
    result_dict, _ = self.evaluator_validation.evaluateRecommender(recommender_instance)
TypeError: evaluateRecommender() missing 1 required positional argument: 'recommender_object'

SearchBayesianSkopt: Search complete. Best config is None: None
